; --------------------------------------------------------------------------------------------------  
; Note Lookups Alternate - 128 bytes each, map MIDI Note# to a VIC register value
; From http://sleepingelephant.com/ipw-web/bulletin/bb/viewtopic.php?t=3643

voice1lookup_alt:
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0                            
   byte 0                            
   byte 0                            
   byte 0                            
   byte 0                            
   byte 0                            
   byte 0                            
   byte 255                   
   byte 134                                              
   byte 141                                              
   byte 147                                              
   byte 153                                              
   byte 159                                  
   byte 164                                  
   byte 170                                  
   byte 174                                  
   byte 179                                  
   byte 183                                  
   byte 187                                  
   byte 191                                  
   byte 195                                  
   byte 198                                  
   byte 201                                  
   byte 204                                  
   byte 207                                  
   byte 210                                  
   byte 212                                  
   byte 215                                  
   byte 217                                  
   byte 219                                  
   byte 221                                  
   byte 223                                  
   byte 225                                  
   byte 226                                  
   byte 228                                  
   byte 230                                  
   byte 231                                  
   byte 232           
   byte 234           
   byte 235           
   byte 236           
   byte 237           
   byte 238           
   byte 239           
   byte 0                
   byte 0                
   byte 0                
   byte 0                
   byte 0                
   byte 0                
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0  
     
voice2lookup_alt:   
   byte 0           
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 255    
   byte 134  
   byte 141  
   byte 147  
   byte 153  
   byte 159  
   byte 164  
   byte 170  
   byte 174  
   byte 179  
   byte 183  
   byte 187  
   byte 191  
   byte 195  
   byte 198  
   byte 201  
   byte 204  
   byte 207  
   byte 210  
   byte 212  
   byte 215  
   byte 217  
   byte 219  
   byte 221  
   byte 223  
   byte 225  
   byte 226  
   byte 228  
   byte 230  
   byte 231  
   byte 232  
   byte 234  
   byte 235  
   byte 236  
   byte 237  
   byte 238  
   byte 239  
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
    
voice3lookup_alt:  
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 255   
   byte 134  
   byte 141  
   byte 147  
   byte 153  
   byte 159  
   byte 164  
   byte 170  
   byte 174  
   byte 179  
   byte 183  
   byte 187  
   byte 191  
   byte 195  
   byte 198  
   byte 201  
   byte 204  
   byte 207  
   byte 210  
   byte 212  
   byte 215  
   byte 217  
   byte 219  
   byte 221  
   byte 223  
   byte 225  
   byte 226  
   byte 228  
   byte 230  
   byte 231  
   byte 232  
   byte 234  
   byte 235  
   byte 236  
   byte 237  
   byte 238  
   byte 239  
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   byte 0   
   
   
voice4lookup_alt: 
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 255  
   byte 134  
   byte 141  
   byte 147  
   byte 153  
   byte 159  
   byte 164  
   byte 170  
   byte 174  
   byte 179  
   byte 183  
   byte 187  
   byte 191  
   byte 195  
   byte 198  
   byte 201  
   byte 204  
   byte 207  
   byte 210  
   byte 212  
   byte 215  
   byte 217  
   byte 219  
   byte 221  
   byte 223  
   byte 225  
   byte 226  
   byte 228  
   byte 230  
   byte 231  
   byte 232  
   byte 234  
   byte 235  
   byte 236  
   byte 237  
   byte 238  
   byte 239  
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0    
   byte 0  

; EOF!
